# -*- coding: utf-8 -*-
"""Русские названия для сопоставления с Name в geotargets-google.csv"""
RU_EN = {
    'Москва': 'Moscow',
    'Санкт-Петербург': 'Saint Petersburg',
    'Новосибирск': 'Novosibirsk',
    'Екатеринбург': 'Yekaterinburg',
    'Казань': 'Kazan',
    'Нижний Новгород': 'Nizhny Novgorod',
    'Челябинск': 'Chelyabinsk',
    'Самара': 'Samara',
    'Омск': 'Omsk',
    'Ростов-на-Дону': 'Rostov-on-Don',
    'Уфа': 'Ufa',
    'Красноярск': 'Krasnoyarsk',
    'Воронеж': 'Voronezh',
    'Пермь': 'Perm',
    'Волгоград': 'Volgograd',
    'Краснодар': 'Krasnodar',
    'Саратов': 'Saratov',
    'Тюмень': 'Tyumen',
    'Тольятти': 'Tolyatti',
    'Ижевск': 'Izhevsk',
    'Барнаул': 'Barnaul',
    'Ульяновск': 'Ulyanovsk',
    'Иркутск': 'Irkutsk',
    'Хабаровск': 'Khabarovsk',
    'Ярославль': 'Yaroslavl',
    'Владивосток': 'Vladivostok',
    'Махачкала': 'Makhachkala',
    'Томск': 'Tomsk',
    'Оренбург': 'Orenburg',
    'Кемерово': 'Kemerovo',
    'Новокузнецк': 'Novokuznetsk',
    'Рязань': 'Ryazan',
    'Астрахань': 'Astrakhan',
    'Пенза': 'Penza',
    'Липецк': 'Lipetsk',
    'Киров': 'Kirov',
    'Чебоксары': 'Cheboksary',
    'Тула': 'Tula',
    'Калининград': 'Kaliningrad',
    'Курск': 'Kursk',
    'Сочи': 'Sochi',
    'Ставрополь': 'Stavropol',
    'Улан-Удэ': 'Ulan-Ude',
    'Тверь': 'Tver',
    'Магнитогорск': 'Magnitogorsk',
    'Иваново': 'Ivanovo',
    'Брянск': 'Bryansk',
    'Белгород': 'Belgorod',
    'Сургут': 'Surgut',
    'Владимир': 'Vladimir',
    'Чита': 'Chita',
    'Архангельск': 'Arkhangelsk',
    'Смоленск': 'Smolensk',
    'Калуга': 'Kaluga',
    'Череповец': 'Cherepovets',
    'Вологда': 'Vologda',
    'Саранск': 'Saransk',
    'Курган': 'Kurgan',
    'Орёл': 'Orel',
    'Владикавказ': 'Vladikavkaz',
    'Грозный': 'Grozny',
    'Мурманск': 'Murmansk',
    'Тамбов': 'Tambov',
    'Петрозаводск': 'Petrozavodsk',
    'Нальчик': 'Nalchik',
    'Йошкар-Ола': 'Yoshkar-Ola',
    'Сыктывкар': 'Syktyvkar',
    'Набережные Челны': 'Naberezhnye Chelny',
    'Севастополь': 'Sevastopol',
    'Симферополь': 'Simferopol',
    'Якутск': 'Yakutsk',
    'Нижневартовск': 'Nizhnevartovsk',
    'Кострома': 'Kostroma',
    'Новороссийск': 'Novorossiysk',
}
